### ISSUE TITLE
bug with limma and column subsets

### ISSUE THREAD

**Issue by assaron** [baba-beda/morpheus#18]
1. Load GSE53986
2. Select subset without #1 samples (columns 2-4, 6-8, 10-12, 14-16) and Ctrl-X
3. Do limma

Limma fails with error:

morpheus-external-latest.min.js:44 OpenCPU error HTTP 400
replacement has 12 rows, data has 16

In call:
`[[<-.data.frame`(`*tmp*`, fieldName, value = structure(c(1L, 
1L, 1L, NA, NA, NA, 2L, 2L, 2L, NA, NA, NA), .Label = c("A", 
"B"), class = "factor"))

morpheus-latest.min.js:9 replacement has 12 rows, data has 16

In call:
`[[<-.data.frame`(`*tmp*`, fieldName, value = structure(c(1L, 
1L, 1L, NA, NA, NA, 2L, 2L, 2L, NA, NA, NA), .Label = c("A", 
"B"), class = "factor"))

**Comment by baba-beda** [comment]
Bug is eliminated. Check in last docker build.
