### ISSUE TITLE
PCA's not working for phenotype data with special symbols

### ISSUE THREAD

**Issue by assaron** [baba-beda/morpheus#2]
1. Open GDS5825
2. Call PCA dialog
3. Select "genotype/variation" for color
4. Click Draw

An error apears: genotype object not found.

I guest it's something to do with a slash in the name.

**Comment by baba-beda** [comment]
Last build shoud've solved this issue. Please, check it out.

**Comment by assaron** [comment]
There is a different problem now, see the screenshot
![2017-01-09-153138_1916x1047_scrot](https://cloud.githubusercontent.com/assets/1040217/21766441/a9c7d304-d67f-11e6-850b-e3b6960e273f.png)

**Comment by baba-beda** [comment]
It occurs, problem was with build, not all new changes were committed to release branches. 
It works well now.
