### ISSUE TITLE
OpenCPU's expression set not updated after manual annotation

### ISSUE THREAD

**Issue by assaron** [baba-beda/morpheus#3]
1. Open GSE14308
2. Do log-adjustment
3. Select some samples, right click on samples annotation field, "annotate selection", name="xx, value="yy".
4. Same as in 3 but with value="zz".
5. Do PCA with xx as color.

Error: object xx not found

**Comment by baba-beda** [comment]
Not reproducible in current release. Expression set is updated after adjustment. Color and size of markers depend only on annotation inside js-code, the whole plot except for markers' coordinates now does not depend on expression set's annotation inside opencpu. Check it out.
